version: '2'

services:
  metabase:
    image: metabase/metabase
    ports:
      - 3333:3000
    volumes:
      - ./plugins/:/plugins

  de-sprint-6:
    image: sindb/de-sprint-6:latest
    container_name: de-sprint-6
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - mydb:/var/lib/postgresql
      - ./src/dags:/lessons/dags
      - ./src/sql:/data/sql
      - ./variables.json:/lessons/variables.json

volumes:
  mydb:
