COPY RAGIMATAMOV_YANDEX_RU__STAGING.users(id, chat_name, registration_dt, country, age) FROM LOCAL STDIN DELIMITER ',' ENCLOSED BY '"' REJECTED DATA AS TABLE RAGIMATAMOV_YANDEX_RU__STAGING.users_rej;
